on: [push, pull_request]
name: Build, and maybe Release
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', '17' ]
    steps:
    - uses: actions/checkout@v3
    - name: Configure Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3.1.1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: make lint
    - name: Compile TypeScript
      run: make build
    - name: List CDK stacks
      run: CDK_DEFAULT_ACCOUNT=foo INTEGRATION_ID=bar make list
  #test: refer to ci/pipeline.ts
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' )
    steps:
    - uses: actions/checkout@v3
    - name: Configure Node.js 16
      uses: actions/setup-node@v3.1.1
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install --no-progress --no-package-lock --no-save
    - name: Install semantic-release extra plugins
      run: npm install \
        @semantic-release/changelog \
        @semantic-release/git \
        --no-progress --no-package-lock --no-save
    - name: Compile TypeScript
      run: make build
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
