name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 17.9.0

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: make lint

    - name: Compile TypeScript
      run: make build

    - name: List CDK stacks
      run: CDK_DEFAULT_ACCOUNT=foo INTEGRATION_ID=bar make list
